### ISSUE TITLE
clicking in codenav window causes source file to open in pane (doesnt navigate to existing source window)

### ISSUE THREAD

**Issue by jasonswearingen** [kdcro101/vscode-typescript-code-navigator#1]
hi, awesome idea and fulfills the only missing detail (code nav) that keeps me going back to VS 2017!

however, a super annoying bug in the June 2018 version of vscode:

if the codenav is open, clicking on the declaration causes the target source file to double-open instead of what I assume is intended: navigating to the existing code file

**Comment by kdcro101** [comment]
@jasonswearingen ,

Thanks for your feedback.

Please update to 1.2.0. (minimum vscode version required is `1.26`)

Just fixed that and other annoying behaviour.

If you have any problems, open issue.
